name: Greetings Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  greet-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Display "Good Day"
        run: echo "Good Day"

  greet-on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Display "Good Night"
        run: echo "Good Night"
